apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
    <proxies>
      <proxy>
        <id>http</id>
        <active>true</active>
        <protocol>http</protocol>
        <host>proxy.nreilly.tamapac.support</host>
        <port>3128</port>
        <nonProxyHosts>nexus</nonProxyHosts>
      </proxy>
      <proxy>
        <id>https</id>
        <active>true</active>
        <protocol>https</protocol>
        <host>proxy.nreilly.tamapac.support</host>
        <port>3128</port>
        <nonProxyHosts>nexus</nonProxyHosts>
      </proxy>
    </proxies>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus:8081/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
